name: Publish CLI
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: false
      - run: vp install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: vp run --filter source-map-viewer build
      # Switch registry to npmjs for publish
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
      - run: vp pm publish --filter source-map-viewer --no-git-checks -- --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
